version: '3.1'
services:
  db:
    image: postgres:14.1
    restart: always
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - .:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    extra_hosts:
      - '${POSTGRES_HOST}:host-gateway'
  myapp:
    depends_on:
      - db
    image: openjdk:11
    container_name: myapp
    env_file:
      - .env
    restart: always
    ports:
      - 8091:8091
    volumes:
      - ./${APP_JAR_NAME}:/app.jar
      - ./logs:/logs
    command: ['java', '-Xms256m', '-Xmx1024m', '-jar', '/app.jar', '${POSTGRES_DB}', '${POSTGRES_USER}', '${POSTGRES_PASSWORD}', '${POSTGRES_HOST}', '${POSTGRES_PORT}', '${BOT_TOKEN}']
    extra_hosts:
      - '${POSTGRES_HOST}:host-gateway'

